// Types
export const types = {
    FETCH_ALL:            'FETCH_ALL',
    FETCH_VEHICLES_ASYNC: 'FETCH_VEHICLES_ASYNC',
    FILL_VEHICLES:        'FILL_VEHICLES',
    FETCH_PEOPLE_ASYNC:   'FETCH_PEOPLE_ASYNC',
    FILL_PEOPLE:          'FILL_PEOPLE',
    FETCH_PLANETS_ASYNC:  'FETCH_PLANETS_ASYNC',
    FILL_PLANETS:         'FILL_PLANETS',
    CANCEL_FETCH:         'CANCEL_FETCH',
};
